export const serviceDetailCard: string;
export const leftCol: string;
export const amount: string;
export const symbol: string;
export const date: string;
export const rightCol: string;
export const component: string;
export const kms: string;
export const comments: string;
