version: '3'

services:
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "4000:4000"
        command: npm run start
        depends_on:
            - "api"
    api:
        build:  ../last-service-server
        volumes:
            - ../last-service-server:/code
        ports: 
            - "4001:4001"
        command: npm run dev
    
        
