export const home: string;
export const loader: string;
export const header: string;
export const body: string;
export const cta: string;
export const empty: string;
export const text1: string;
export const text2: string;
export const text3: string;
